### ISSUE TITLE
Error closing QGIS when Command is active

### ISSUE THREAD

**Issue by anitagraser** [NathanW2/qgiscommand#2]
Closing QGIS causes AttributeError: 'NoneType' object has no attribute 'Resize'.

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/anita_000/.qgis2/python/plugins\qgiscommand\qgiscommand.py", line 61, in eventFilter
    if event.type() == QEvent.Resize:
AttributeError: 'NoneType' object has no attribute 'Resize'

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.1-Wien Wien, exported

Python path: ['C:/Users/anita_000/.qgis2/python/plugins\processing_prepair', 'C:/Users/anita_000/.qgis2/python/plugins\processing', 'C:/OSGEO4~1/apps/qgis/./python', u'C:/Users/anita_000/.qgis2/python', u'C:/Users/anita_000/.qgis2/python/plugins', 'C:/OSGEO4~1/apps/qgis/./python/plugins', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg', 'c:\osgeo4~1\apps\python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\OSGEO4~1\bin\python27.zip', 'C:\OSGEO4~1\apps\Python27\DLLs', 'C:\OSGEO4~1\apps\Python27\lib', 'C:\OSGEO4~1\apps\Python27\lib\plat-win', 'C:\OSGEO4~1\apps\Python27\lib\lib-tk', 'C:\OSGEO4~1\bin', 'C:\OSGEO4~1\apps\Python27', 'C:\OSGEO4~1\apps\Python27\lib\site-packages', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\PIL', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\win32', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\setuptools-0.6c11-py2.7.egg-info', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'C:/Users/anita_000/.qgis2//python', 'C:\Users\anita_000\.qgis2\python\plugins\mmqgis/forms', '.', '/home/nathan/dev/data-dev/qgiscommand', 'C:\OSGEO4~1\apps\qgis\python\plugins\fTools\tools']

**Comment by klakar** [comment]
Confirming the issue!
A lot of error dialogs opens, the more I try to close them, the more opens... Have to "kill" QGIS to end it.

Ett fel har inträffat vid Pythonexekvering:

Traceback (most recent call last):
  File "/home/klakar/.qgis2/python/plugins/qgiscommand/qgiscommand.py", line 61, in eventFilter
AttributeError: 'NoneType' object has no attribute 'Resize'

Python version:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

QGIS version:
2.8.1-Wien Wien, exported

Python sökväg: ['/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/requests-2.0.1-py2.7.egg', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/nose_html-1.1-py2.7.egg', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/gsconfig-0.6.9-py2.7.egg', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/gsimporter-0.1-py2.7.egg', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/python_dateutil-2.2-py2.7.egg', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/six-1.7.3-py2.7.egg', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/lxml-3.3.5-py2.7-win32.egg', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs/httplib2-0.9-py2.7.egg', '/home/klakar/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/klakar/.qgis2/python', u'/home/klakar/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/klakar/.qgis2//python', '/home/klakar/.qgis2/python/plugins/opengeo/ext-libs', '/home/nathan/dev/data-dev/qgiscommand', '/usr/share/qgis/python/plugins/fTools/tools']

**Comment by NathanW2** [comment]
Should be fixed now
